/*
 * MATLAB Compiler: 4.0 (R14)
 * Date: Wed Apr 22 21:08:40 2009
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe" "cascada.m" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_cascada_public_data[] = {'3', '0', '8', '1', '9',
                                                   'D', '3', '0', '0', 'D',
                                                   '0', '6', '0', '9', '2',
                                                   'A', '8', '6', '4', '8',
                                                   '8', '6', 'F', '7', '0',
                                                   'D', '0', '1', '0', '1',
                                                   '0', '1', '0', '5', '0',
                                                   '0', '0', '3', '8', '1',
                                                   '8', 'B', '0', '0', '3',
                                                   '0', '8', '1', '8', '7',
                                                   '0', '2', '8', '1', '8',
                                                   '1', '0', '0', 'C', '4',
                                                   '9', 'C', 'A', 'C', '3',
                                                   '4', 'E', 'D', '1', '3',
                                                   'A', '5', '2', '0', '6',
                                                   '5', '8', 'F', '6', 'F',
                                                   '8', 'E', '0', '1', '3',
                                                   '8', 'C', '4', '3', '1',
                                                   '5', 'B', '4', '3', '1',
                                                   '5', '2', '7', '7', 'E',
                                                   'D', '3', 'F', '7', 'D',
                                                   'A', 'E', '5', '3', '0',
                                                   '9', '9', 'D', 'B', '0',
                                                   '8', 'E', 'E', '5', '8',
                                                   '9', 'F', '8', '0', '4',
                                                   'D', '4', 'B', '9', '8',
                                                   '1', '3', '2', '6', 'A',
                                                   '5', '2', 'C', 'C', 'E',
                                                   '4', '3', '8', '2', 'E',
                                                   '9', 'F', '2', 'B', '4',
                                                   'D', '0', '8', '5', 'E',
                                                   'B', '9', '5', '0', 'C',
                                                   '7', 'A', 'B', '1', '2',
                                                   'E', 'D', 'E', '2', 'D',
                                                   '4', '1', '2', '9', '7',
                                                   '8', '2', '0', 'E', '6',
                                                   '3', '7', '7', 'A', '5',
                                                   'F', 'E', 'B', '5', '6',
                                                   '8', '9', 'D', '4', 'E',
                                                   '6', '0', '3', '2', 'F',
                                                   '6', '0', 'C', '4', '3',
                                                   '0', '7', '4', 'A', '0',
                                                   '4', 'C', '2', '6', 'A',
                                                   'B', '7', '2', 'F', '5',
                                                   '4', 'B', '5', '1', 'B',
                                                   'B', '4', '6', '0', '5',
                                                   '7', '8', '7', '8', '5',
                                                   'B', '1', '9', '9', '0',
                                                   '1', '4', '3', '1', '4',
                                                   'A', '6', '5', 'F', '0',
                                                   '9', '0', 'B', '6', '1',
                                                   'F', 'C', '2', '0', '1',
                                                   '6', '9', '4', '5', '3',
                                                   'B', '5', '8', 'F', 'C',
                                                   '8', 'B', 'A', '4', '3',
                                                   'E', '6', '7', '7', '6',
                                                   'E', 'B', '7', 'E', 'C',
                                                   'D', '3', '1', '7', '8',
                                                   'B', '5', '6', 'A', 'B',
                                                   '0', 'F', 'A', '0', '6',
                                                   'D', 'D', '6', '4', '9',
                                                   '6', '7', 'C', 'B', '1',
                                                   '4', '9', 'E', '5', '0',
                                                   '2', '0', '1', '1', '1'
                                                   , '\0'};

const char *__MCC_cascada_name_data = "cascada";

const char *__MCC_cascada_root_data = "";

const unsigned char __MCC_cascada_session_data[] = {'7', 'F', '2', 'B', '0',
                                                    'C', '8', '7', 'D', '1',
                                                    'B', '3', '3', 'F', 'D',
                                                    '1', '8', '4', '1', '9',
                                                    '0', '9', 'E', '7', '4',
                                                    '7', '3', '0', '5', '0',
                                                    'E', 'E', 'F', '0', 'E',
                                                    'E', '5', '5', '6', '6',
                                                    '6', 'A', 'E', 'B', '7',
                                                    'B', '3', '8', 'F', 'B',
                                                    '8', '1', '6', '3', '7',
                                                    'F', '8', 'F', 'F', 'A',
                                                    '5', 'E', '2', '5', 'D',
                                                    'D', '1', '4', '7', 'C',
                                                    'B', 'E', 'E', 'D', '5',
                                                    '2', '6', '9', '5', 'D',
                                                    'F', '2', '0', '8', 'F',
                                                    '0', '6', '4', '3', '8',
                                                    'F', '7', '0', 'C', '7',
                                                    'D', '0', '3', '4', 'C',
                                                    '6', 'C', '8', 'C', 'C',
                                                    '9', '4', '9', '1', 'D',
                                                    'A', '7', '9', 'F', 'D',
                                                    '3', 'B', '6', '1', 'A',
                                                    '9', 'F', 'D', '7', '1',
                                                    'C', '3', '9', '9', 'A',
                                                    '2', '4', '0', '8', '0',
                                                    '8', '7', '3', 'E', 'E',
                                                    '8', 'D', 'F', 'C', '9',
                                                    'E', '6', '9', '5', '1',
                                                    'E', 'E', '0', '0', '6',
                                                    'F', '9', '9', '2', 'B',
                                                    'C', '2', '7', '2', '2',
                                                    '8', '0', '6', '9', 'B',
                                                    'B', '3', 'D', '6', '4',
                                                    '2', '9', '5', '4', 'F',
                                                    '8', '3', 'F', '8', '1',
                                                    'F', '3', '1', '5', 'C',
                                                    'C', 'B', '7', '8', 'E',
                                                    'B', 'D', '2', 'E', '1',
                                                    '5', '1', '5', '6', '4',
                                                    '2', '4', '2', 'A', '7',
                                                    '5', '2', 'A', '7', '4',
                                                    'F', '0', '0', 'B', '3',
                                                    '8', '8', '5', 'D', '6',
                                                    '0', '8', 'F', '6', '5',
                                                    'B', '4', '2', '4', 'D',
                                                    'E', 'C', '2', '2', 'C',
                                                    'D', '5', 'E', 'E', '5',
                                                    '5', '2', '1', 'B', 'C',
                                                    'E', '5', 'B', '2', 'B',
                                                    '3', '\0'};

const char *__MCC_cascada_matlabpath_data[] = {"cascada/",
                                               "toolbox/compiler/deploy/",
                                               "$TOOLBOXMATLABDIR/general/",
                                               "$TOOLBOXMATLABDIR/ops/",
                                               "$TOOLBOXMATLABDIR/lang/",
                                               "$TOOLBOXMATLABDIR/elmat/",
                                               "$TOOLBOXMATLABDIR/elfun/",
                                               "$TOOLBOXMATLABDIR/specfun/",
                                               "$TOOLBOXMATLABDIR/matfun/",
                                               "$TOOLBOXMATLABDIR/datafun/",
                                               "$TOOLBOXMATLABDIR/polyfun/",
                                               "$TOOLBOXMATLABDIR/funfun/",
                                               "$TOOLBOXMATLABDIR/sparfun/",
                                               "$TOOLBOXMATLABDIR/scribe/",
                                               "$TOOLBOXMATLABDIR/graph2d/",
                                               "$TOOLBOXMATLABDIR/graph3d/",
                                               "$TOOLBOXMATLABDIR/specgraph/",
                                               "$TOOLBOXMATLABDIR/graphics/",
                                               "$TOOLBOXMATLABDIR/uitools/",
                                               "$TOOLBOXMATLABDIR/strfun/",
                                               "$TOOLBOXMATLABDIR/imagesci/",
                                               "$TOOLBOXMATLABDIR/iofun/",
                                               "$TOOLBOXMATLABDIR/audiovideo/",
                                               "$TOOLBOXMATLABDIR/timefun/",
                                               "$TOOLBOXMATLABDIR/datatypes/",
                                               "$TOOLBOXMATLABDIR/verctrl/",
                                               "$TOOLBOXMATLABDIR/codetools/",
                                               "$TOOLBOXMATLABDIR/helptools/",
                                               "$TOOLBOXMATLABDIR/winfun/",
                                               "$TOOLBOXMATLABDIR/demos/",
                                               "toolbox/local/",
                                               "toolbox/compiler/"};
const int __MCC_cascada_matlabpath_data_count = 32;

const char *__MCC_cascada_mcr_application_options[] = { "" };
const int __MCC_cascada_mcr_application_option_count = 0;
const char *__MCC_cascada_mcr_runtime_options[] = { "" };
const int __MCC_cascada_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


